name: Deploy Curvas MVP Application
on:
  push:
    branches: [feat/mvp]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Java Version
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Build Project
        run: mvn clean install -DskipTests

      - name: Login Docker Hub
        run: docker login -u ${{secrets.DOCKER_USERNAME}} -p ${{secrets.DOCKER_PASSWORD}}

      - name: Build Docker Image
        run: docker build -t gilbertomoj/curvas-back-mvp .

      - name: Push Curvas Docker image
        run: docker push gilbertomoj/curvas-back-mvp

  deploy:
    needs: build
    runs-on: self-hosted
    steps:
      - name: Pull image from docker hub
        run: docker pull gilbertomoj/curvas-back-mvp

      - name: Remove docker container
        run: docker rm -f curvas-back-mvp

      - name: Run docker container
        run: docker run -d -p 8080:8080 -e DATABASE_USERNAME='${{secrets.DATABASE_USERNAME}}' -e DATABASE_PASSWORD='${{secrets.DATABASE_PASSWORD}}' -e DATABASE_URL='${{secrets.DATABASE_URL}}' -e JWT_SECRET='${{secrets.JWT_SECRET}}' --name curvas-back-mvp gilbertomoj/curvas-back-mvp